# Render.com Deployment Configuration

services:
  - type: web
    name: multi-agent-backend
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: LLM_MODEL
        value: mixtral-8x7b-32768
    healthCheckPath: /health
    