# Render.com Deployment - OPTIMIZED FOR FREE TIER

services:
  - type: web
    name: multi-agent-system
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: PORT
        value: 8000
      # Memory optimization settings
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /tmp/models
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers
      # Lightweight embedding model
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      # Reduce chunk sizes
      - key: CHUNK_SIZE
        value: 300
      - key: TOP_K_RETRIEVAL
        value: 3
    healthCheckPath: /health
    autoDeploy: true